export let labList = [
  {
    id: 0,
    cardType: "tallWide",
    title: "Volvo Trucks Configurator",
    client: "Volvo Trucks | Umantech",
    description: `Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
    category: [
      "Software Development",
      "Creative Coding",
      "Electronic Engeneering",
    ],
    technology: [
      "Arduino",
      "Hardware Hacking",
      "Processing",
      "Resolume",
      "Ableton Live",
    ],
    backgroundImage: "https://picsum.photos/id/575/800/530",
    content: {
      type: "video",
      videoID: "5HadnuUHlPo",
    },
  },
  {
    id: 1,
    cardType: "wide",
    title: "NBA",
    client: "NBA",
    description: `Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
    category: [
      "Software Development",
      "Creative Coding",
      "Electronic Engeneering",
    ],
    technology: [
      "Arduino",
      "Hardware Hacking",
      "Processing",
      "Resolume",
      "Ableton Live",
    ],
    backgroundImage: "https://picsum.photos/id/575/800/530",
    content: {
      type: "video",
      videoID: "5HadnuUHlPo",
    },
  },
  {
    id: 2,
    cardType: "tall",
    title: "O Parque",
    client: "Gamaro",
    description: `Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
    category: [
      "Software Development",
      "Creative Coding",
      "Electronic Engeneering",
    ],
    technology: [
      "Arduino",
      "Hardware Hacking",
      "Processing",
      "Resolume",
      "Ableton Live",
    ],
    backgroundImage: "https://picsum.photos/id/575/800/530",
    content: {
      type: "video",
      videoID: "5HadnuUHlPo",
    },
  },
  {
    id: 3,
    cardType: "tallWide",
    title: "DDX Digital Dealer Experience",
    client: "Volkswagen",
    description: `Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
    category: [
      "Software Development",
      "Creative Coding",
      "Electronic Engeneering",
    ],
    technology: [
      "Arduino",
      "Hardware Hacking",
      "Processing",
      "Resolume",
      "Ableton Live",
    ],
    backgroundImage: "https://picsum.photos/id/575/800/530",
    content: {
      type: "video",
      videoID: "5HadnuUHlPo",
    },
  },
  {
    id: 4,
    cardType: "normal",
    title: "Toyota Visitor Center",
    client: "Toyota",
    description: `Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
    category: [
      "Software Development",
      "Creative Coding",
      "Electronic Engeneering",
    ],
    technology: [
      "Arduino",
      "Hardware Hacking",
      "Processing",
      "Resolume",
      "Ableton Live",
    ],
    backgroundImage: "https://picsum.photos/id/575/800/530",
    content: {
      type: "video",
      videoID: "5HadnuUHlPo",
    },
  },
  {
    id: 5,
    cardType: "normal",
    title: "Espaço do Conhecimento",
    client: "GS1 Brasil",
    description: `Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
    category: [
      "Software Development",
      "Creative Coding",
      "Electronic Engeneering",
    ],
    technology: [
      "Arduino",
      "Hardware Hacking",
      "Processing",
      "Resolume",
      "Ableton Live",
    ],
    backgroundImage: "https://picsum.photos/id/575/800/530",
    content: {
      type: "video",
      videoID: "5HadnuUHlPo",
    },
  },
  {
    id: 6,
    cardType: "normal",
    title: "Volkswagen Polo and Virtus Lauching",
    client: "Volkswagen",
    description: `Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
    category: [
      "Software Development",
      "Creative Coding",
      "Electronic Engeneering",
    ],
    technology: [
      "Arduino",
      "Hardware Hacking",
      "Processing",
      "Resolume",
      "Ableton Live",
    ],
    backgroundImage: "https://picsum.photos/id/575/800/530",
    content: {
      type: "video",
      videoID: "5HadnuUHlPo",
    },
  },
  {
    id: 7,
    cardType: "tallWide",
    title: "Volkswagen Lauching",
    client: "Volkswagen Venezuela",
    description: `Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
    category: [
      "Software Development",
      "Creative Coding",
      "Electronic Engeneering",
    ],
    technology: [
      "Arduino",
      "Hardware Hacking",
      "Processing",
      "Resolume",
      "Ableton Live",
    ],
    backgroundImage: "https://picsum.photos/id/575/800/530",
    content: {
      type: "video",
      videoID: "5HadnuUHlPo",
    },
  },
  {
    id: 8,
    cardType: "tall",
    title: "Volkswagen Lauching",
    client: "Volkswagen Argentina",
    description: `Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
    category: [
      "Software Development",
      "Creative Coding",
      "Electronic Engeneering",
    ],
    technology: [
      "Arduino",
      "Hardware Hacking",
      "Processing",
      "Resolume",
      "Ableton Live",
    ],
    backgroundImage: "https://picsum.photos/id/575/800/530",
    content: {
      type: "video",
      videoID: "5HadnuUHlPo",
    },
  },
];
