export let labList = [
  {
    id: 0,
    cardType: "tallWide",
    title: "Web 3D Mustang",
    client: "Umantech",
    description: `A POC to test the capabilities of rendering WebGL to create a car configurator. Access: <a href="https://jhun.com.br/mustang/" target="_blank"><span>Web 3D Mustang</span></a>`,
    category: ["Software Development", "Creative Coding"],
    technology: ["Javascript", "Three.js", "WebGL"],
    backgroundImage:
      "https://website-jhun.s3-sa-east-1.amazonaws.com/images/mustang.jpg",
    content: {
      type: "video",
      videoID: "s4n2v-vQ7uc",
    },
  },
  {
    id: 1,
    cardType: "tallWide",
    title: "Projection Game",
    client: "VZLAB",
    description: `To test an idea of <span>merging the Point Cloud</span> of multiple Kinects for a job we were producing, I created a test game to receive the blob data generated by the tracked physical scene. Both, <span>Merged Kinect Point Cloud App and Game App</span> were developed using Processing.`,
    category: ["Software Development", "Creative Coding"],
    technology: ["Hardware Hacking", "Processing"],
    backgroundImage:
      "https://website-jhun.s3-sa-east-1.amazonaws.com/images/projection-game.jpg",
    content: {
      type: "video",
      videoID: "PZ4ovB9frE0",
    },
  },
  {
    id: 2,
    cardType: "wide",
    title: "Space Invaders Web VR",
    client: "Me, myself",
    description: `Well, I wanted to test programming <span>VR for the Web</span>. For that, I chose the classic game <span>Space Invaders</span> as the theme of my prototype. I was impressed with the ability of VR for the Web, I was able to use the 2 controls on my Oculus Quest and processed a good amount of simultaneous objects well. Nice!`,
    category: ["Software Development", "Creative Coding"],
    technology: ["Three.js", "Javascript", "Oculus Quest", "WEB VR"],
    backgroundImage:
      "https://website-jhun.s3-sa-east-1.amazonaws.com/images/space-invaders.jpg",
    content: {
      type: "video",
      videoID: "m9uLKM1Xwe4",
    },
  },
  {
    id: 3,
    cardType: "normal",
    title: "Portuguese Word Clock",
    client: "Me, myself",
    description: `Inspired by the various Word Clock made in the world, I built a mini version in Portuguese (Brazil). I wanted a version that could be small enough to be a cube that would fit in the palm of my hand. Done.`,
    category: ["Software Development", "Creative Coding"],
    technology: ["Arduino", "Hardware Hacking"],
    backgroundImage:
      "https://website-jhun.s3-sa-east-1.amazonaws.com/images/wordclock.jpg",
    content: {
      type: "video",
      videoID: "p68IIw4nnYA",
    },
  },
  {
    id: 4,
    cardType: "wide",
    title: "3D RGB LED Matrix [RAIN]",
    client: "VZLAB",
    description: `There are many led cubes (8x8x8 leds) on the internet, but few have a triple dimension <span>(8x8x24 leds)</span> and even less have the animation data outside the microcontroller. The challenge in this project was to be able to control this <span>amount (1,536) of RGB LEDs</span> in an orderly way and receiving the <span>data in Real-time</span> through the Serial port.`,
    category: [
      "Software Development",
      "Creative Coding",
      "Electronic Engeneering",
    ],
    technology: ["Arduino", "Hardware Hacking", "Openframeworks", "Processing"],
    backgroundImage:
      "https://website-jhun.s3-sa-east-1.amazonaws.com/images/3drgb-led3.jpg",
    content: {
      type: "video",
      videoID: "MriWF8PfE9w",
    },
  },
  {
    id: 5,
    cardType: "tall",
    title: "3D RGB LED Matrix [TWO]",
    client: "VZLAB",
    description: `There are many led cubes (8x8x8 leds) on the internet, but few have a triple dimension <span>(8x8x24 leds)</span> and even less have the animation data outside the microcontroller. The challenge in this project was to be able to control this <span>amount (1,536) of RGB LEDs</span> in an orderly way and receiving the <span>data in Real-time</span> through the Serial port.`,
    category: [
      "Software Development",
      "Creative Coding",
      "Electronic Engeneering",
    ],
    technology: ["Arduino", "Hardware Hacking", "Openframeworks", "Processing"],
    backgroundImage:
      "https://website-jhun.s3-sa-east-1.amazonaws.com/images/3drgb-led2.jpg",
    content: {
      type: "video",
      videoID: "BhIAUhGeKFU",
    },
  },
  {
    id: 6,
    cardType: "tall",
    title: "3D RGB LED Matrix [ONE]",
    client: "VZLAB",
    description: `There are many led cubes (8x8x8 leds) on the internet, but few have a triple dimension <span>(8x8x24 leds)</span> and even less have the animation data outside the microcontroller. The challenge in this project was to be able to control this <span>amount (1,536) of RGB LEDs</span> in an orderly way and receiving the <span>data in Real-time</span> through the Serial port.`,
    category: [
      "Software Development",
      "Creative Coding",
      "Electronic Engeneering",
    ],
    technology: ["Arduino", "Hardware Hacking", "Openframeworks", "Processing"],
    backgroundImage:
      "https://website-jhun.s3-sa-east-1.amazonaws.com/images/3drgb-led.jpg",
    content: {
      type: "video",
      videoID: "gsy3l7-ZZdM",
    },
  },
  {
    id: 7,
    cardType: "tallWide",
    title: "DISCOVID 19.2",
    client: "Me, myself",
    description: `I wanted to build this self-balanced robot representing my votes so that we can win this <span>fight against COVID 19</span>. May <span>science, technology and people</span> be allies in this journey.`,
    category: [
      "Software Development",
      "Creative Coding",
      "Electronic Engeneering",
    ],
    technology: ["Arduino", "Hardware Hacking", "Processing"],
    backgroundImage:
      "https://website-jhun.s3-sa-east-1.amazonaws.com/images/discovid.jpg",
    content: {
      type: "video",
      videoID: "mUK1I-rE91k",
    },
  },
  {
    id: 8,
    cardType: "normal",
    title: "Interactive Projection",
    client: "Me, myself",
    description: `Interactive Projection at home`,
    category: ["Software Development", "Creative Coding"],
    technology: ["Hardware Hacking", "Processing"],
    backgroundImage:
      "https://website-jhun.s3-sa-east-1.amazonaws.com/images/interactive-projection.jpg",
    content: {
      type: "video",
      videoID: "I1_9fhqK4Oo",
    },
  },
  {
    id: 9,
    cardType: "wide",
    title: "Pulley sensing",
    client: "ArchiMotu",
    description: `Sensing prototype with optical encoder`,
    category: ["Software Development", "Electronic Engeneering"],
    technology: ["Arduino", "Hardware Hacking", "IoT", "Cloud"],
    backgroundImage:
      "https://website-jhun.s3-sa-east-1.amazonaws.com/images/sensor-pulley.jpg",
    content: {
      type: "video",
      videoID: "tA_C9yJnTzw",
    },
  },
  {
    id: 10,
    cardType: "normal",
    title: "Mobile Camera Tracking",
    client: "Me, myself",
    description: `The idea was to track the camera of the <span>mobile device</span>, so that the objects captured in the physical space were positioned in the virtual 3D scene.
    For this, I attached the <span>Intel Realsense T265</span> to the mobile device, thus making it possible to track the position and rotation of the camera.`,
    category: ["Software Development", "Creative Coding"],
    technology: [
      "Hardware Hacking",
      "Processing",
      "Intel Realsense",
      "Camera tracking",
    ],
    backgroundImage:
      "https://website-jhun.s3-sa-east-1.amazonaws.com/images/camera-tracking.jpg",
    content: {
      type: "video",
      videoID: "RYjvAsAw_-E",
    },
  },
  {
    id: 11,
    cardType: "tallWide",
    title: "Quarantined Tech Mind",
    client: "Me, myself",
    description: `A piece to try to relieve the mind during quarantine. It was not easy. Technically, I wanted to explore the WebGL rendering for web, space sound and light. That's it. Access: <a href="https://jhun.com.br/quarantined/" target="_blank"><span>Quarantined Tech Mind</span></a>`,
    category: ["Software Development", "Creative Coding"],
    technology: ["Javascript", "Three.js", "WebGL"],
    backgroundImage:
      "https://website-jhun.s3-sa-east-1.amazonaws.com/images/quarantined.jpg",
    content: {
      type: "video",
      videoID: "7qtz1px-sh0",
    },
  },
  {
    id: 12,
    cardType: "normal",
    title: "Haptics Wearable",
    client: "Me, myself",
    description: `A prototype of a wearable to be used in conjunction with the <span>HTC VIVE VR</span>. This wearable has a microcontroller, battery and haptic attached. In the test, I made an integration with a Unity application, so that when the user steps on something in the virtual world, this haptics is activated at the configured intensity, for example, it can be used in kicking or walking movements. In the final version it is used together with a <span>Vive Tracker</span>.`,
    category: ["Software Development", "Electronic Engeneering"],
    technology: [
      "Arduino",
      "Hardware Hacking",
      "Haptics",
      "HTC Vive VR",
      "HTC Vive Tracker",
    ],
    backgroundImage:
      "https://website-jhun.s3-sa-east-1.amazonaws.com/images/haptics-wearable.jpg",
    content: {
      type: "video",
      videoID: "eNOmqNyoCmU",
    },
  },
];
